#cloud-config
ssh_pwauth: no
users:
  - name: user
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - ${SSH_KEY}
write_files:
  - path: /root/vm_prep.sh
    permissions: "0744"
    content: |
      #!/bin/bash
      sudo apt update -y && sudo apt install docker.io docker-compose -y
      sudo usermod -aG docker user
      newgrp docker
runcmd:
  - sleep 120
  - sudo -i
  - /root/vm_prep.sh