---

name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select the Terraform action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_yc_zone: "ru-central1-b"
      TF_VAR_ssh_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_yc_cloud_id: ${{ secrets.CLOUD_ID }}
      TF_VAR_yc_folder_id: ${{ secrets.FOLDER_ID }}

    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
        
      - name: Yandex Cloud authentication
        run: echo ${{ secrets.CLOUD_KEY }} | base64 -d > ./cloud_key.json

      - name: Initialize Terraform
        run: |
          terraform init -backend-config="access_key=$ACCESS_KEY" -backend-config="secret_key=$SECRET_KEY"
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Terraform Plan
        if: ${{ github.event.action == 'plan' }}
        run: terraform plan

      - name: Terraform Apply
        if: ${{ github.event.action == 'apply' }}
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ github.event.action == 'destroy' }}
        run: terraform destroy -auto-approve
